### ISSUE TITLE
Move to gitbooks

### ISSUE THREAD

**Issue by Conaws** [kristianmandrup/datascript-tutorial#3]
https://www.gitbook.com/

Would make it easier to read and to contribute

**Comment by kristianmandrup** [comment]
Cool :) Thanks!

**Comment by kristianmandrup** [comment]
Moved the book to gitbook.com as requested

https://www.gitbook.com/book/kmandrup/datomic-and-datascript

However I'm still learning the ins/outs of how to use it and link it correctly to github etc. Any help/advice would be much appreciated!

**Comment by kristianmandrup** [comment]
I linked my gitbook book to my original github account. Then I downloaded the gitbook app for Mac.
Then I rewrote (copy/paste + edit) most of the chapters in order to setup proper indexing.
Then synced changes. Now my gitbook book is kinda out of sync with my updated repo, not sure how to resync it!? Damn!

**Comment by kristianmandrup** [comment]
For anyone out there, please feel free to to port this project to Gitbook :) Thanks!
